# Generated by Django 5.2.6 on 2025-10-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_attendancerecord_status_alter_employee_photo'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='admin_panel.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
